### ISSUE TITLE
Can you kindly share links to other interesting M5  solutions

### ISSUE THREAD

**Issue by Sandy4321** [andrewdoss/M5-forecasting#1]
Great code thank you very much 
Can you kindly share links to other interesting M5  solutions
Especially what help understand what was done in 
1st place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/163684
2nd place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164599
3d place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164374
4th place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/163216
7th place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164826
etc..

**Comment by andrewdoss** [comment]
Thanks for the compliment! Glad you found the code useful.

Unfortunately, I did not stick with the contest through the end so I am not familiar with the final winning approaches (otherwise, I would be happy to help).

**Comment by andrewdoss** [comment]
Thanks for the compliment! Glad you found the code useful.

Unfortunately, I did not stick with the contest through the end so I am not familiar with the final winning approaches (otherwise, I would be happy to help).
